### ISSUE TITLE
Do not require that a dependency's test-dependencies are present on disk

### ISSUE THREAD

**Issue by tchupp** [klazuka/intellij-elm#112]
I restarted IntelliJ after updating to version 2.0.0 of the plugin, and my Elm projects all prompted me with "No Elm projects found"
After hitting "Attach elm.json" and navigating to the proper file, IntelliJ presents me with the error message:
```
org.elm.workspace.ProjectLoadException: 
Could not load elm-explorations/test (Constraint(low=1.1.0, high=2.0.0, lowOp=LESS_THAN_OR_EQUAL, highOp=LESS_THAN))
```

Here is my elm.json:
```
{
    "type": "application",
    "source-directories": [
        "src/elm"
    ],
    "elm-version": "0.19.0",
    "dependencies": {
        "direct": {
            "elm/browser": "1.0.0",
            "elm/core": "1.0.0",
            "elm/html": "1.0.0",
            "elm/http": "1.0.0",
            "elm/json": "1.0.0",
            "elm/random": "1.0.0",
            "elm/time": "1.0.0",
            "elm/url": "1.0.0",
            "rundis/elm-bootstrap": "5.0.0"
        },
        "indirect": {
            "avh4/elm-color": "1.0.0",
            "elm/virtual-dom": "1.0.0"
        }
    },
    "test-dependencies": {
        "direct": {},
        "indirect": {}
    }
}
```

**Comment by klazuka** [comment]
Given the `elm.json` file that you posted, it shouldn’t even be trying to load elm-explorations/test. So that’s weird. Did you recently remove it?

But in any case, can you please verify that `elm-explorations/test` actually exists in `~/.elm/0.19.0/package/`?

Another thing you can try is opening the Elm tool window (on the right-hand border of the IntelliJ window) and click the Refresh button.

If all else fails, in the IntelliJ menu bar, select File -> Invalidate Caches and restart. But that shouldn’t be necessary.

One more question, which version of the plugin were you running before now?

**Comment by tchupp** [comment]
I never had the elm-explorations/test package installed for this project.
And yes it does exist in the Elm cache.

Re-freshing the project in the Tool window didn’t help.
I’ll try clearing the cache and post a follow up.

**Comment by tchupp** [comment]
After invalidating I got the message that I was missing a different dependency that I definitely never had as a direct dependency, `rtfeldman/elm-hex`

I ended up `elm install`-ing that, which prompted another dependency, etc.
I followed the tree until the project eventually imported.

I'll leave this up to you if you want to close the issues or not.
My direct issue has been fixed, and I'm unblocked from working...
But seeing as this wasn't an issue with the previous version of the plugin, I'm sure someone else will run into this in the future.

Thanks!

**Comment by klazuka** [comment]
Is it possible that there's an `elm.json` file somewhere on your computer that has these dependencies, possibly at the root of your IntelliJ project? I don't see how the plugin could possibly be cooking-up things like "rtfeldman/elm-hex", so it must be reading it off the disk somewhere. 

The plugin does try to auto-discover `elm.json` files in some situations, so it's possible that the project which was attached was not the one that you expected. If it happens again, please check the list of projects in the Elm tool window (right-side border of IntelliJ) to verify the path of any `elm.json` files in there.

Meanwhile, I will double-check the auto-import code.

**Comment by klazuka** [comment]
Nevermind, I was able to reproduce the problem using your `elm.json` file. I will investigate and fix. Thanks for reporting.

**Comment by klazuka** [comment]
The problem is related to the indirect dependency on "avh4/elm-color", which has the following in its `elm.json`:
```
  "test-dependencies": {
    "elm-explorations/test": "1.1.0 <= v < 2.0.0",
    "rtfeldman/elm-hex": "1.0.0 <= v < 2.0.0",
    "NoRedInk/elm-json-decode-pipeline": "1.0.0 <= v < 2.0.0"
  }
```

Those are the packages that you were prompted to install, which solves the mystery.

I just need to relax things in the plugin so that it doesn't try to load (or at least fails more gracefully) a dependency's test-dependencies.

**Comment by klazuka** [comment]
For anyone else who runs into this problem, you can get the fix from here: https://github.com/klazuka/intellij-elm/releases/tag/v2.0.1

I will also submit a new build to JetBrains, but it will take several days before it becomes available from within the IDE.

**Comment by tchupp** [comment]
I’m glad you were able to find the problem with what I provided! Thank you for responding so quickly, and thank you for maintaining this plugin 😁
