### ISSUE TITLE
Generate function from type annotation doesn't use camelCase

### ISSUE THREAD

**Issue by samrensenhouse** [klazuka/intellij-elm#125]
Given a type annotation `myFunc : CustomTypeAlias -> Bool`

I would expect `myFunc customTypeAlias =` but instead I get `myFunc customtypealias =`

Love the auto create feature, and I think this would make it a lot better.

**Comment by klazuka** [comment]
I actually just fixed this last weekend in #123. I will probably do a release this weekend.

**Comment by klazuka** [comment]
The fix is out now in a pre-release build: https://github.com/klazuka/intellij-elm/releases/tag/v2.0.3-rc1

That link has an attached zip file which contains the compiled plugin. It’s pretty easy to install. 

So if you get a chance, give it a try and let me know if you run into any problems. Assuming everything is fine, I will submit it to JetBrains on Monday for publishing.
