### ISSUE TITLE
Find Usages should exclude type annotations

### ISSUE THREAD

**Issue by klazuka** [klazuka/intellij-elm#177]

**Comment by ajalt** [comment]
I added the ability to exclude type annotations in #118. Do you think that they should never be included?

**Comment by klazuka** [comment]
I remembered that you had done something like that. Yes, I think they should be filtered out. I'm guessing that the `element !is ElmTypeAnnotation` condition which you added is not working the way we would expect (or that the Psi tree has changed since then).

**Comment by ajalt** [comment]
It still works for me. You have to uncheck the "Show import statement" box.
![untitled](https://user-images.githubusercontent.com/1109214/50355658-49f03d80-0504-11e9-8183-48a99c9fdd2b.png)

**Comment by klazuka** [comment]
Oh, I didn't realize that. It's definitely counter-intuitive as who would think that it is an "import" statement.

One one hand I hate to hide information totally, but on the other hand, it seems like there is almost no value at all in having type annotations show up in Find Usages. So, yeah, I'm inclined to just filter them out entirely.

**Comment by Birowsky** [comment]
I agree with @klazuka

**Comment by KasMA1990** [comment]
I agree that type annotation should be left out completely; I was just about to open an issue for it 🙂

**Comment by Birowsky** [comment]
@KasMA1990 now that you know how that there is a way to filter them out, do you still think that the plugin needs to be non-standard and hide the annotations regardless whether the user asked for it or not?

It's true that I learned about that filtering feature BECAUSE of this issue, but since then, I don't have that problem anymore. Ergo, I changed my mind and I'm not convinced that they should be completely removed.

**Comment by KasMA1990** [comment]
I would still remove them. For one I think including type annotations under imports is also a bit non-standard, and it would get annoying if I actually want to see imports. But in my mind, the type annotation never counts as a usage anyway, so I would never expect to see it in there, no matter what settings I have.

**Comment by ajalt** [comment]
I think that it would be nice to filter out annotations, but after some more investigation, I'm fairly certain it's not possible.

The Find Usages system calls our [FindUsagesProvider](https://github.com/klazuka/intellij-elm/blob/master/src/main/kotlin/org/elm/ide/search/ElmFindUsagesProvider.kt) to scan each file for the usage types. I had thought it might be possible to exclude the annotation in the scanner, but it turns out this doesn't work. The scanner output is only used to populate a per-file map indicating what string exist in each file (and whether they're present in comments/strings/code). So excluding the annotation token doesn't do anything.

The actual usages list is populated by resolving all PSI reference elements whose text matches the element you're looking for. We can't conditionally resolve a reference, so the annotation is always included.

**Comment by klazuka** [comment]
Well, that settles it. I think the only way forward here would be to lobby JetBrains to allow plugins more control, but I don't have the time.

For anyone who arrives at this issue looking for a workaround, see https://github.com/klazuka/intellij-elm/issues/177#issuecomment-449451683
