### ISSUE TITLE
Plugin tries to load non-existant package when attaching elm.json

### ISSUE THREAD

**Issue by MartinSStewart** [klazuka/intellij-elm#216]
When attaching an elm.json file to my project, I get the following error
`org.elm.workspace.ProjectLoadException: Could not load elm-lang/core (5.1.1 <= v < 6.0.0). Is it installed?`

The elm.json however doesn't list elm-lang/core since that's an 0.18 package and I'm using 0.19

**Details**
OS: Windows 10
Elm.json contents: [elmjson.zip](https://github.com/klazuka/intellij-elm/files/2752117/elmjson.zip)

**Comment by klazuka** [comment]
Just to get this out of the way, would you mind verifying that you have configured the Elm plugin to point at the 0.19 binary and not 0.18? (see screenshot)
<img width="1047" alt="screen shot 2019-01-12 at 9 47 46 am" src="https://user-images.githubusercontent.com/84525/51076581-2c1f7f80-164f-11e9-91a7-303ce11c93e9.png">

I feel like I ran into this problem once before, and it was something to do with accidentally running `elm make` on the 0.18 binary when I thought it was calling 0.19. Unfortunately, I don't remember the particulars. Maybe you might want to look at each one of your direct dependencies and make sure that it can be found in `C:/Users/<user>/AppData/Roaming/elm/0.19.0/`?

You might also want to try deleting your local `elm-stuff` directory as well as deleting `C:/Users/<user>/AppData/Roaming/elm/0.19.0/`. Then run `elm make` on your project again to install the dependencies.

**Comment by klazuka** [comment]
Ok. I'm not surprised that you had to run `elm reactor` (or `elm make`) after clearing `elm-stuff` and the global Elm package cache: intellij-elm will not actually try to install any dependencies on your behalf. I should at least show a warning in such cases, and so I've created a new issue to track that (#219).

I still don't understand why stuff got corrupted in the first place, but I feel pretty confident that it wasn't caused by intellij-elm since it doesn't actually install anything.
