### ISSUE TITLE
Incorrectly flagged case statements

### ISSUE THREAD

**Issue by tylerperkins** [klazuka/intellij-elm#260]
The first `case` statement in each `.elm` file of the tutorial is flagged, "Case expression is not exhaustive". This happens in the Elm plugin v2.2.3 and v2.2.2. I'm using the latest versions of IntelliJ IDEA Ultimate 2018.3.4 (build #U-183.5429.30), Elm 0.19.0 (via [MacOS installer](https://github.com/elm/compiler/releases/download/0.19.0/installer-for-mac.pkg)), and node v11.9.0.

To verify that the bug did not depend upon my particular Elm project, I created a new project from Evan's [elm-architecture-tutorial](https://github.com/evancz/elm-architecture-tutorial). Here's a screenshot of file [`examples/04-maybe.elm`](https://github.com/evancz/elm-architecture-tutorial/blob/master/examples/04-maybe.elm) in IntelliJ with the Elm plugin:

![screen shot 2019-02-10 at 1 51 39 pm](https://user-images.githubusercontent.com/607877/52539412-0fa06100-2d3b-11e9-9414-76a58c321a1b.png)
When you mouse over the flagged `case`, you can see the error message:
![screen shot 2019-02-10 at 1 48 31 pm](https://user-images.githubusercontent.com/607877/52539376-bb957c80-2d3a-11e9-81ac-cb71dbde3850.png)

(I've separated this issue from [this one in elm-external-tools](https://github.com/jlagerweij/elm-external-tools/issues/8), because it arrises even when Elm External Tools is not installed.)

**Comment by ajalt** [comment]
Thanks for the reproducable example!

So this issue is caused by the fact that that repo has multiple files in the same source directory without module declarations, and each file declares a `Msg` type. They're separate programs in the same project. We currently look up the `Msg` declaration by name and module, but we don't currently have a way to differentiate between the various `Msg` declarations, so we end up selecting the wrong one sometimes, causing the errors. 

@klazuka I looked into using `ModuleScope` and `ImportScope` instead of `ElmLookup`, but I couldn't get that working with aliases. Maybe there's a way to add the file to element to `ElmLookup.findByName`?

Here's a failing unit test for `ElmIncompletePatternInspectionTest`:

```kotlin
    fun `test multiple files with no module and same type name`() = checkFixIsUnavailableByFileTree("Add missing case branches", """
--@ File1.elm
type Msg = Foo | Bar
--@ File2.elm
type Msg = Bar | Baz
--@ File2.elm
type Msg = Qux

foo : Msg -> ()
foo it =
    case{-caret-} it of
        Qux ->
            ()
""")
```

**Comment by klazuka** [comment]
Thanks @ajalt. I'll fix it.
