### ISSUE TITLE
Easy elm-format integration

### ISSUE THREAD

**Issue by klazuka** [klazuka/intellij-elm#266]
It should be really easy to use elm-format from within IntelliJ.

Some of this work is done in the `master` branch but has not yet been released.

- [x] create a ‘run elm-format’ Action to which the user can assign a keybinding
- [x] prevent the “Undo reload from disk” dialog (see #261 )
- [x] on-save hook to invoke elm-format (with project setting to opt-in/out)
- [x] if on-save hook is disabled, show the user how to assign a keybinding in project settings?
- [x] refusue to run elm-format if the Psi tree contains any errors
- [x] verify that format-on-save hook does not add to the undo stack
- [x] allow the user to specify the path to elm-format (rather than infering it)
- [x] show the version number of elm-format (or some kind of green/red status) in the settings UI
- [x] finally, update/delete the elm-format integration guide from the README
- [ ] create a PR against elm-format repo updating the plugin status table

**Comment by klazuka** [comment]
@FloWi this is where I'm tracking the final polish to make the elm-format integration awesome. My goal is to have all of this done by the end of the month. You can take on as much (or as little) work as you wish. Just let me know so that I know what to work on. Thank you 🙏

**Comment by FloWi** [comment]
@klazuka I'll work on these points:

I can work on all points except this one: `improve how errors are shown when elm-format fails due to parse errors (or just refusue to run elm-format if the Psi tree contains any errors)`

Elm-format returns an ansi-colored string if you call it with illegal elm code. We could display that in a console, but I think it's better to just not run it. 

In the scalafmt-plugin they use a default keybinding for the reformat action (Cmd+Shift+L). I'll try it out later to see how IDEA handles conflicts with scalafmt keybinding. Don't know, if you can have two actions using the same keybinding (because they should never be active at the same time). This way we could provide a no-config-just-runs-experience :)

If the default keybinding works, the point `if on-save hook is disabled, show the user how to assign a keybinding in project settings` would be obsolete.

I tried to create a nicer settings panel, but Swing is driving me nuts :-/ Do you have more experience with it? For now I'll just add a checkbox to enable/disable elm-format-on-save. We can leave the option to configure an alternative path to elm-format for later.

**Comment by klazuka** [comment]
Yeah, showing the elm-format output may be tricky. I'm sure it can be done, but probably the best thing to do right now is to disable the elm-format action when there are parse errors in the current file. This is easy to check by calling `PsiTreeUtil.hasErrorElements`.

It would be nice to avoid the key-binding UI all together by piggy-backing on Cmd+Option+L. If that works, let's do it.

I don't know much about Swing. IntelliJ does have a [layout DSL](https://github.com/JetBrains/intellij-community/tree/master/platform/platform-impl/src/com/intellij/ui/layout) for making this sort of thing easier. As for specifying an alternate path to elm-format, let's hold off on that. The current behavior should cover most people, and they can add a symlink as a workaround if needed. Eventually we will have to support it, but for now let's keep it simple. I don't want to commit to persisting any more data without thinking about how other Elm tools would be handled.

**Comment by FloWi** [comment]
Yeah, I also found the layout DSL. But this doesn't allow more sophisticated UIs I think. I asked my colleagues - most of them try to avoid swing like the plague :) One mentioned that he uses netbeans just for designing UIs, since it generates java code that can be copy&pasted into another project. 

But I like the idea with the symlinks. Should do the trick for now.

**Comment by klazuka** [comment]
@FloWi I just read the source for IntelliJ's keymap configuration system and mapped it all out. I'll do the work to add a "set/change keybinding" button directly in the Elm settings UI. This way we can make it easy for the user to define the keyboard shortcut without getting lost in IntelliJ's keymap UI.

**Comment by FloWi** [comment]
Nice! I'm curious to see how you're going to implement it. I love oss :) I'm going to update the docs here and in the elm-format repo when you're done.

**Comment by klazuka** [comment]
Let's not touch the docs until the UI is finalized. It's very nearly done, but I want to give it a few days before we start taking screenshots and stuff.

**Comment by klazuka** [comment]
I updated the todo list at the top of this issue. After looking at how things are installed on Windows, we should allow the user to explicitly specify the path to elm-format.

**Comment by FloWi** [comment]
I remembered the domain of your mail address - I guess it makes you the perfect candidate for checking how things work on windows 😛 

Btw: for `verify that format-on-save hook does not add to the undo stack` take a look at #303.

**Comment by FloWi** [comment]
For `show the version number of elm-format (or some kind of green/red status) in the settings UI` I created #304.

I thought a bit more about the settings ui and its different states.
Do you have an idea how to model or implement them?

Wish we had union types from elm here in kotlin-world - it'd be much easier to model the different states of elm-compiler and elm-format.

Here are the cases that come to mind:
- elm-compiler cases:
  - not found
  - found, but no version / invalid version
  - found and valid
- elm-format cases:
  - paths
    - manual path
    - vs.
    - same path as the elm-compiler (might not be necessary and a button "use same as above" could do the trick)
  - not found
  - found, but no version / invalid version
  - found and valid

**Comment by klazuka** [comment]
I actually don't use Windows (but AJ does).

Nice work on finishing so many things yesterday.

In terms of the settings UI, I will take the task of:

1. making it look nice (taking into consideration that we will also want to add `elm-test` binary path)
2. making the path to `elm-format` configurable.

This last thing will require some changes to how we're automatically suggesting binary directories, and it's probably best if I do it.

Once that's done, the last thing to do is update documentation and ship it.

**Comment by FloWi** [comment]
Nice that you want to add elm-test support. 

I'm curious to see how you improve the stateful swing stuff. It'd be great to have it like elm's view- and update-functions.

**Comment by klazuka** [comment]
I just merged the changes to `ElmToolchain` so that the `elm-format` path is configurable. See #311.

Getting close to shipping this feature now 😄

**Comment by klazuka** [comment]
This is done now. The last step (updating the elm-format readme, https://github.com/avh4/elm-format/pull/488) will have to wait until after we release the new software.

@FloWi thank you so much for taking the initiative to make this awesome. 🙏

**Comment by FloWi** [comment]
You're very welcome! I learned a lot (about plugins and kotlin) and it was great working with you.
I just pulled your code and tried it out. It's a much better experience!
