### ISSUE TITLE
A type alias with a field called export is shown as error

### ISSUE THREAD

**Issue by samrensenhouse** [klazuka/intellij-elm#297]
Any type alias with keywords as fields seem to cause errors.

![image](https://user-images.githubusercontent.com/22641341/52965414-59f09600-336a-11e9-846f-f4f8ca13eda0.png)

I tried this with words like type or import and also got an error.

**Comment by klazuka** [comment]
@samrensenhouse `export` used to be a reserved keyword, so that's where the error is coming from. I didn't know that it's no longer reserved. I did some digging around just now and found out that it, and a few others, were removed in 2016 (https://github.com/elm/compiler/commit/f7c25d263b48c2db78cce14f74095440438aef4f).

So this is a bug in our plugin, and I will fix it.
