### ISSUE TITLE
Support Elm-Projects

### ISSUE THREAD

**Issue by d3xter** [klazuka/intellij-elm#30]

**Comment by klazuka** [comment]
Can you provide some more details?

**Comment by d3xter** [comment]
We should be able to create a new Elm-Project just by doing File -> New -> Project -> Elm
and this should setup a minimal project (elm-package.json, src/)

Fyi, I'm already working on this

**Comment by klazuka** [comment]
Cool. I thought you were referring to parsing the `elm-package.json` to infer the project structure (which is something that I definitely want to do because the situation now is pretty bad, especially if you use `elm-test`). I had been waiting to do it until Elm 0.19 because (a) that manifest file is changing and (b) I don't have much time.

**Comment by d3xter** [comment]
Thats only the first step :)

Next steps could be:

- Be able to import an Elm-Project by reading `elm-package.json`
- Dependencies show up inside "External Libraries"
- Sync basic Project-Data (Name, Version, Source-Folders) with `elm-package.json` both ways
- Maybe be able to add/search/remove Dependencies directly from inside Intellij and sync them with `elm-package.json`

**Comment by klazuka** [comment]
Priorities sound good. The only adjustment I would make is to do two-way sync last (one-way sync from the JSON file to IntelliJ structure should be good enough)

**Comment by klazuka** [comment]
@d3xter I'm working on this now because it's a blocker for Elm 0.19 (#41)

Right now, my code cheats by just assuming that everything in the local `elm-stuff` directory has been installed by the user. But in Elm 0.19, dependencies will be stored globally in the user's home directory. 
We will need to read the `elm-package.json` file in order to know which modules in the global cache are relevant.

This work should also indirectly fix #15 and #21.

**Comment by d3xter** [comment]
I figured that starting this way is easier, because I haven't found much stuff about how to import an existing project.

Ultimately we should use the External System Integration (https://www.jetbrains.org/intellij/sdk/docs/reference_guide/frameworks_and_external_apis/external_system_integration.html) 

Sounds fine to me, just give me a heads up once the groundwork is finished,
then I'll integrate my Project-Creation-Code.

**Comment by klazuka** [comment]
@d3xter your approach is definitely easier, and if it weren't for Elm 0.19, it would be a reasonable place to start. This stuff is poorly documented, but, as always, the intellij-rust plugin is a gold mine on how to hook into IntelliJ and how to do tests.

The good news is that we don't strictly need to do the full "External System Integration"—but we will need to do some tricky stuff when resolving dependencies to make sure that we look at the correct version.

**Comment by klazuka** [comment]
@d3xter I just landed the foundation for this stuff in commit 5df2782. It's probably still a bit too raw for you to start building on. But you might want to read the commit message and look things over.

I ended up using Jackson for decoding the JSON since that's what I'm familiar with, but I'm kinda worried about [jackson-module-kotlin](https://github.com/FasterXML/jackson-module-kotlin)'s runtime compatibility with whatever version of Kotlin is bundled with the user's IntelliJ. It might be smarter to go back and use a simpler JSON library like you did.

The thing I'm least happy with is construction of the ElmToolchain object. It would be nice to cache the Elm compiler version on this object, but that needs to be done by invoking an external process, which is slow, and, in many places, IntelliJ will throw an exception if you block for too long. So I need to make things async. Which is tricky because IntelliJ wants to instantiate things synchronously, so we need to do a 2 stage init. Anyway, just mentioning that to make it clear that there are probably bigger changes coming.

**Comment by d3xter** [comment]
What would you say if I just start with the Elm-Module-Type and a basic Module-Creation that just creates the "src"-Folder and marks it as a "Source Folder" without doing anything with elm-package.json?

That would mean Users should be able to create Elm-Projects inside Intellij like they can with other languages and we can add the elm-package.json-stuff when you are done with the other parts

**Comment by klazuka** [comment]
That plan sounds good to me.

I landed basic support for running elm-make from within the IDE in commit 54f230033405507a6a350aae2948ad49978d472a. It's not exposed in the UI because there's still a lot of work to be done. Especially related to presenting any compile errors in nice way.

I've also been looking into porting [fluxxu/elm-hot-loader](https://github.com/fluxxu/elm-hot-loader) to work with Elm 0.19 and to remove the hard dependency on webpack. My thinking is that we can run a web-server inside IntelliJ and serve the user's Elm app with hot module reloading. But I've put that work on pause because the Elm 0.19 compiler's output is still changing.
