### ISSUE TITLE
Unused variables are shown as used

### ISSUE THREAD

**Issue by samrensenhouse** [klazuka/intellij-elm#319]
![image](https://user-images.githubusercontent.com/22641341/53368033-4f577300-390d-11e9-91ff-dcca1b9c029d.png)

It appears that if you use certain words it will make the variables show up as used. I am guessing because I am shadowing html names. I don't feel like this is expected behaviour though.

**Comment by klazuka** [comment]
Are you referring to the `title` and `body` parameters here? If so, I suspect that this may be caused by an optimization that we do to avoid doing too much work. If a string (such as `body`) occurs a *lot* in the project, we will skip the usage check. But I would really only expect this to kick in for really common things like `i`, `x`, `div`, etc. Can you do a search in your project for `body` and see how many results there are?

**Comment by samrensenhouse** [comment]
Yep! I am referring to those. There are seven results for body, and nineteen of title. That excluded results of those inside actual strings.

**Comment by klazuka** [comment]
the heuristic that it uses to avoid an expensive search is as follows:

- if the word occurs in 10 or more files: too expensive!
- if any file containing the word is larger than ~500KB: too expensive!

So in the case of `body`, maybe it's in a huge file (either an Elm file or even something else like an HTML file)?

And in the case of `title`, I'm guessing that it's spread across more than 10 files?

I'm especially curious about the sizes of the files which `body` is contained in. If it turns out to be something like a giant HTML file, then maybe there's something I can do to restrict those from the scope.

**Comment by ajalt** [comment]
If we went back to restricting the search scope for parameters to just the containing declaration, would that avoid this problem?

**Comment by klazuka** [comment]
> If we went back to restricting the search scope for parameters to just the containing declaration, would that avoid this problem?

Yes, in this case I think there's a really simple fix for parameters. But I wanted to find out a little more just to get a feel for other situations where it won't be as easy to restrict the scope.

**Comment by samrensenhouse** [comment]
Ah, I didn't realize that it included the whole project. I assumed it only used elm files. I had only been searching .elm files. If I include html and css, the count is over 10.

If I include html, scss, and js files the file count for title usage is 14 files.

If these word counts include just strings, which I thought they didn't, then my package-lock.json file would be included which has a lot of usages, and that file is massive.

**Comment by klazuka** [comment]
@samrensenhouse ok, thanks. #323 will fix your problem (function parameters).
