### ISSUE TITLE
Non default test folder path

### ISSUE THREAD

**Issue by mingan** [klazuka/intellij-elm#340]
I'm working on a project which has a non-standard project structure from the Elm perspective:

```
elm-package.json
app/
  frontend/
    elm/
      Main.elm
      tests/
         elm-package.json
         Main/
           Tests.elm
```

It's currently on Elm 0.18, structure is trying to fit into Ruby on Rails with Webpacker. Elm can be compiled, tests can be run directly via elm-test but the IDE plugin doesn't seem to be able to handle it. There are two issues (which I assume are related):

1. All testing dependencies are marked as unresolved when imported into the test files as well as used - this reduces the plugin to syntax highlighting with a lot of red visual noise. This has been true for several versions now but I'm bringing it up since you did so much work on integrating elm-test recently.
2. Trying to run the tests in the IDE prints:
```
No tests found in the test/ (or tests/) directory.

NOTE: Make sure you're running elm-test from your project's root directory, where its elm-package.json lives.
```
Both seem to point to the test directory being hardcoded. If it's true, could it become a configurable option (similar to elm-test and elm-format binaries) in some future version?

**Comment by klazuka** [comment]
1. you must attach *both* `elm-package.json` files to the IntelliJ project. The file at the root of your project and the file at `app/frontend/elm/tests/`
2. that's caused by #324, which has been fixed and merged into `master`, but it hasn't yet been shipped. I intend to make a bug-fix release sometime this week.

**Comment by mingan** [comment]
1. Ok, I wouldn't have expected that.
2. Great!

Thank you!

**Comment by klazuka** [comment]
@mingan there should be a yellow banner at the top of the `.elm` file when the plugin cannot locate the corresponding `elm-package.json` file. I'm guessing that that wasn't the case here?

I suspect that the problem is due to how you have your directories structured where one Elm project is nested within the source-directory of another. I think in that case we do not show the warning banner.

**Comment by mingan** [comment]
I removed the second `elm-package.json` to check and there is no banner or anything. I guess this setup is pretty unusual and 0.19 solves it by specifying test dependencies in `elm.json`.
