### ISSUE TITLE
Fatal error initializing plugin org.elm.klazuka

### ISSUE THREAD

**Issue by ewingrj** [klazuka/intellij-elm#357]
I just tried to install the plugin and get the above error after restarting IntelliJ.

I'm using IntelliJ Idea 2017.1.6 on macOS and version 2.2.4 of the plugin.

Any ideas?

**Comment by klazuka** [comment]
@ewingrj I don't see your error, but I'm almost certain that the problem is that you are using IntelliJ 2017. There was a regression where I started using some IntelliJ API that was not available in 2017. Would it be possible for you to upgrade to a minimum of 2018.2? 

Generally I try to keep compatibility going backwards, but sometimes it's hard to keep things straight among the various versions.

**Comment by ewingrj** [comment]
hmm,

I'm using this within a Django project, which requires IntelliJ Idea Ultimate support. Unfortunately I only have a fallback license for 2017.

I'll try out the this plugin on the community edition to see if it's worth updating my license
