### ISSUE TITLE
RIGHT_BRACE expected, got '}'

### ISSUE THREAD

**Issue by mordrax** [klazuka/intellij-elm#392]
When the model is empty I get the RIGHT_BRACE error and elm format does not run even though elm make will compile fine.

This error does not appear if `type alias Model = { test : Int }`

![image](https://user-images.githubusercontent.com/4709169/56542247-40114080-65b1-11e9-98ce-06b5eab14eab.png)

WebStorm 2018.1.5
Build #WS-181.5281.31, built on June 15, 2018
JRE: 1.8.0_152-release-1136-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-47-generic

Elm plugin 2.2.4

**Comment by klazuka** [comment]
I cannot reproduce the false positive syntax error. I suspect that it's a bug in intelliJ, especially since the error message makes no sense (the expect and actual tokens are the same).

But some good news, starting in version 3.1.1 of the Elm plugin, it will still allow you to run elm-format even if it thinks that there are syntax errors.
