### ISSUE TITLE
Exception in plugin Elm (3.1.2)

### ISSUE THREAD

**Issue by emthornber** [klazuka/intellij-elm#428]
com.intellij.openapi.extensions.impl.PicoPluginExtensionInitializationException: org.frawa.elmtest.run.ElmTestRunConfigurationProducer has unsatisfied dependency: class org.frawa.elmtest.run.ElmTestConfigurationFactory among unsatisfiable dependencies: [[class org.frawa.elmtest.run.ElmTestConfigurationFactory], [class org.frawa.elmtest.run.ElmTestRunConfigurationType]] where DefaultPicoContainer (root) was the leaf container being asked for dependencies.

Don't know what triggered the exception.  It's the second time today so I'll keep an eye out.

**Comment by klazuka** [comment]
Maybe you had installed the [intellij-elm-test-runner](https://github.com/frawa/intellij-elm-test-runner)  plugin before that code got merged directly into this plugin? If so, it could be causing a conflict and you should uninstall it.

**Comment by emthornber** [comment]
Keith,

Ah - hadn’t realised it was Either/Or for those plugins.  I will uninstall
and report back.

AAMOI - does the plugin recognise that there is already an index.html and
automatically output a .js file when compiling ?

Thanks
—
MarkT

On 9 July 2019 at 15:17:08, Keith Lazuka (notifications@github.com) wrote:

Maybe you had installed the intellij-elm-test-runner
<https://github.com/frawa/intellij-elm-test-runner> plugin before that code
got merged directly into this plugin? If so, it could be causing a conflict
and you should uninstall it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/klazuka/intellij-elm/issues/428?email_source=notifications&email_token=AACLEF4NHCSPQYFAXQSASNLP6SMWHA5CNFSM4H7FOY4KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZQNAEQ#issuecomment-509661202>,
or mute the thread

**Comment by klazuka** [comment]
No, the current integration with the Elm compiler is limited: it only runs the compiler in order to detect compile-time errors. Most compile-time errors should be shown directly within IntelliJ automatically because of our parser, reference resolver and type checker, but there may be some things that slip through (especially in un-opened files). So we provide the `elm` binary as the final safety-net. The generated code goes to `/dev/null`.

In the future I would like to make this work so that it can generate and run code.

**Comment by emthornber** [comment]
Keith,

Presumably the Elm plugin needs to have an ‘SDK' defined/integrated with
IntelliJ

Shout if you have some grunt work you’d like to offload

Regards
—
MarkT
Software Engineer who goes back to Hollerith cards and paper tape.

On 9 July 2019 at 16:12:32, Keith Lazuka (notifications@github.com) wrote:

No, the current integration with the Elm compiler is limited: it only runs
the compiler in order to detect compile-time errors. Most compile-time
errors should be shown directly within IntelliJ automatically because of
our parser, reference resolver and type checker, but there may be some
things that slip through (especially in un-opened files). So we provide the
elm binary as the final safety-net. The generated code goes to /dev/null.

In the future I would like to make this work so that it can generate and
run code.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/klazuka/intellij-elm/issues/428?email_source=notifications&email_token=AACLEF3GBOQPW6WLNS22N73P6STGBA5CNFSM4H7FOY4KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZQSQ5I#issuecomment-509683829>,
or mute the thread

**Comment by klazuka** [comment]
It's unclear to me how the SDK thing works in IntelliJ. It seems to be a vestigal Java thing, and I have tried to avoid it as much as possible. The intellij-rust plugin also seems to ignore the SDK concept.

The big thing blocking this feature (compiling and emitting JS/HTML) is changing it so that it is managed as a run configuration which may open a tool window to show output. Right now it's just a tool window, and that limits our abilities to configure things. My long-term plan has been to switch it over to a run config (similar to how the `elm-test` integration works thanks to @frawa), that will allow you to define mulitple configurations, persist them, and provide standard UI for working with them.

You're welcome to work on it if you want. I just moved across the US, so I'm busy with move-related stuff.

**Comment by emthornber** [comment]
Keith,

Is it me missing something or just the vagaries of JetBrains - the
behaviour of ’New | Project | …’ is different between IntelliJ IDEA and
WebStorm.

IDEA has a ‘Elm Project’ menu item which causes `elm init` to be run in new
project top directory.
WebStorm doesn’t have such a menu item nor the ‘behind-the-scenes’
initialisation'

Puzzled
—
MarkT

On 12 July 2019 at 16:24:42, Keith Lazuka (notifications@github.com) wrote:

Closed #428 <https://github.com/klazuka/intellij-elm/issues/428>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/klazuka/intellij-elm/issues/428?email_source=notifications&email_token=AACLEF55ZZASTGWVNUXLW3LP7CO3TA5CNFSM4H7FOY4KYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOSPELGIA#event-2479403808>,
or mute the thread

**Comment by klazuka** [comment]
Known issue: #414. The "new project" system in IntelliJ is complicated and not documented at all. If you want to dig in and identify the problem, that would be great. But it may be difficult.
