### ISSUE TITLE
type signature generation intention ignores type aliases

### ISSUE THREAD

**Issue by CSchank** [klazuka/intellij-elm#433]
When using the intention to create a type signature, we get something like:

`displayScreen : { a | screen : Screen, positions : List (Float, Float), ... } -> Html Msg`

instead of using the type alias for that record:

`displayScreen : Model -> Html Msg`.

Is this something that is possible to fix, or too difficult and thus it was left alone? Perhaps if it's not sure whether it is actually using a certain type alias, it could provide the user a list of possible type aliases that can be chosen.

Thank you!

**Comment by ajalt** [comment]
Type inference for a function only examines the body of that function. The type we infer matches what the Elm compiler prints out if you call the function with an incorrect type.

Having said that, it would definitely be nicer to be able to generate aliases for big records like this. But in order to do that, we'd need to look at call sites and match them up to any aliases we see. That's imperfect, and will break caller code if we guess wrong. It's especially complicated by the fact that aliased records can be nested arbitrarily inside other types, and that multiple aliases can be used for the same record.

So for now we stick with the simpler, always correct solution of using the full record.

**Comment by klazuka** [comment]
@CSchank here's a simple workaround: you can use IntelliJ's "extend selection" feature to syntactically select the big record literal. So after generating the type annotation move the cursor up into the big record literal. Then press `Option-UpArrow` a couple times until the entire record is selected. Then type `Model` to replace it all.

If the record type occurs multiple times in the signature (e.g. an update function which takes a model and returns a model), you can press `Ctrl-g` when the record is selected, and it will add a selection for the next occurrence of the selected text. Then type `Model` and it will replace _both_ of them at the same time.

I know it's not ideal, but once you get used to it, it can be pretty fast.

**Comment by CSchank** [comment]
@ajalt thank you for your insight. I figured as much. Better to have a fully working solution than one that's potentially better but could fail.

@klazuka great, thank you, this sounds like a good workaround. I'm a bit new to IntelliJ so I'm still learning all the ins and outs.

Thanks again!
