### ISSUE TITLE
Indent type alias of record to allow for parsing/formatting

### ISSUE THREAD

**Issue by akselw** [klazuka/intellij-elm#443]
When creating a new type alias of a record, I usually type the following `type alias Test = {` which causes IntelliJ to insert a closing brace. Resulting in the following:

![Screenshot 2019-07-24 at 13 30 44](https://user-images.githubusercontent.com/5320566/61790390-57adce80-ae17-11e9-9555-af61f6199a6a.png)

My instinct is then to always press Enter, which results in the following:

![Screenshot 2019-07-24 at 13 33 13](https://user-images.githubusercontent.com/5320566/61790531-bc692900-ae17-11e9-9dfc-b365ff85d927.png)

Since there is no indentation inserted, elm-format is unable to format the record correctly, and I have to manually insert spaces at the start of the two last lines to get elm-format to work again. It would be great if the plugin could insert those spaces for me, so I wouldn't have to.

**PS**: I know that `elm-format` actually puts the newline before the opening brace, not after, and if I were to press Enter before typing the opening brace, everything works, but after a lot of time, I still can't get my fingers to type the Enter first, so I don't really have any confidence that I will be able to learn it 😄

**Comment by klazuka** [comment]
That sounds reasonable. In general we could do a much better job with auto-indenting, but I've been reluctant to go all-in and implement real whitespace formatting because it would have to match elm-format exactly. But there is probably some small hack we could do here to make it nicer (I think I already do something similar for function bodies)

**Comment by akselw** [comment]
Fixed by #693
