### ISSUE TITLE
False positive error message in case...of expression

### ISSUE THREAD

**Issue by MartinSStewart** [klazuka/intellij-elm#460]
In this code example, the first case is correctly marked as an error but the third case is also marked as an error despite it returning the correct type.

![Screen Shot 2019-08-07 at 2 59 23 PM](https://user-images.githubusercontent.com/5068391/62624822-3aebbd80-b924-11e9-8aca-2fa5bce1f3e6.png)

**Comment by ajalt** [comment]
So what's happening is that, when inferring a case expression, we infer the type of the whole expressions as the type of the first branch. So the string branch is marked as an error because it doesn't match the type of the first branch. Our type inference works bottom up, so we don't know what type the case expression will be assigned to when we're looking at the branches, which is why we just try to match it to the first branch.
