### ISSUE TITLE
Version 3.4.0 causes all imports to be marked as unresolved references

### ISSUE THREAD

**Issue by MartinSStewart** [klazuka/intellij-elm#473]
(This issue went away after I deleted the elm-stuff folder and restarted intellij but I figured it might be worth reporting anyway)

![image](https://user-images.githubusercontent.com/5068391/63294335-52368d80-c2ca-11e9-9ba0-667c8b6fc069.png)

I upgraded from 3.3.0 and found that none of the imports from any modules are being resolved. This includes both internal and external modules.

**Comment by klazuka** [comment]
do you have an Elm 0.18 or 19 project?

**Comment by klazuka** [comment]
(nevermind, I see `Browser.Dom`). The `elm-stuff` directory is not used at all by the plugin for Elm 0.19+ projects. So that shouldn't matter. 

The only reason why I might think that restarting IntelliJ would have fixed anything is that one of the big changes in 3.4.0 is widespread adoption of "stubs" to allow type inference to run over the entire project without actually parsing any files (besides the file that you are editing). These stubs are cached on disk, and IntelliJ should regenerate them during indexing. Maybe there was a race condition where it cached the references before the new index was generated?

I'm going to close this, but I'll keep my eye out for related issues. If you see it happen again, definitely let me know.
