### ISSUE TITLE
Unable to resolve some references

### ISSUE THREAD

**Issue by lanarchyste** [klazuka/intellij-elm#479]
Hi,

I have a strange behavior with the plugin 3.4.0 on Intellij IDEA 2019.2

When I import an ELM 0.18 project for the first time, all references are resolved. But when I close Intellij IDEA, and re-open the project, most references can not be resolved.
<img width="1468" alt="Screenshot 2019-08-21 at 10 12 02" src="https://user-images.githubusercontent.com/4154672/63414437-274c5680-c3fc-11e9-9939-3989b1b6de53.png">

I have checked that the elm-package.json file is attached to the project and elm-compiler is defined

I do not have the problem with a project in ELM 0.19

With Intellij IDEA 2018.3.6 and the ELM 3.2.1 plugin, I have no problem

**Comment by klazuka** [comment]
There have been reports of a similar bug affecting 0.18 projects in WebStorm (#442 and #470), but I haven't heard of it affecting IDEA. Please try marking the `elm-stuff` directory as **not** excluded.

This used to work fine, but something happened in 2019.2. Elm 0.19 projects don't have this problem because the package dependencies are stored in the global package cache, not in the `elm-stuff` directory.

Let me know if this fixes your problem and I will see what I can do about putting a fix in the code for Elm 0.18.

**Comment by lanarchyste** [comment]
It works by marking the _elm-stuff_ directory as not excluded !

Thanks for the tip.
