### ISSUE TITLE
Unused value highlighting is gone

### ISSUE THREAD

**Issue by z5h** [klazuka/intellij-elm#522]
As of 3.4.3 intellij-elm no longer highlights unused values.

**Comment by klazuka** [comment]
Can you provide an example? It works for me (and the tests pass).

**Comment by z5h** [comment]
It seems to be buggy. Sometimes works, sometimes not.

<img width="175" alt="image" src="https://user-images.githubusercontent.com/81692/66056503-377c4900-e505-11e9-8764-3530e0e49d12.png">

<img width="702" alt="image" src="https://user-images.githubusercontent.com/81692/66056667-7ad6b780-e505-11e9-8eaa-147b96510cec.png">

**Comment by klazuka** [comment]
I think the problem is that those really short ones are too expensive to search and we bail out early. In this case, a false negative is expected. 

We use an index to find all occurrences of each value, say, `a`. For a short string like this, it may result in so many candidate files that even with the index, if we were to search them all it would slow everything down. So we only do the "unused value" check for text which is reasonably unique. Sorry.
