### ISSUE TITLE
Tab size

### ISSUE THREAD

**Issue by ivan-kleshnin** [klazuka/intellij-elm#567]
Hi Keith. Thanks for this great plugin! 

Is there an option to control tab size? As far as I know the Elm community is not settled on 2 vs 4 spaces. So we need a toggler. I see that tab size (number of spaces) is inherited from "Default Language". It's good but it's not enough and some behaviors ignore that default. For example:

```elm
myfunction : Int -> Int
myfunction = -- press Enter
    _ -- gets here no matter of actual tab size
```

**Comment by klazuka** [comment]
The problem is that we have not integrated with IntelliJ's whitespace formatting system. I've avoided it because I'm afraid of how it may "fight" with `elm-format`, and I don't want to go down the rabbit hole of trying to emulate `elm-format`.

It might be possible for us to implement an ad-hoc solution assuming that we can query the tab size in IntelliJ's general preferences. I bet we can, but I've never looked into it. It shouldn't be too hard to implement... I just haven't heard any requests for the feature.
