### ISSUE TITLE
Code folding

### ISSUE THREAD

**Issue by DoctypeRosenthal** [klazuka/intellij-elm#61]
It seems, your marvelous plugin doesn't support code folding (records, functions, ...) yet. 
Is it planned?

**Comment by klazuka** [comment]
Not prioritized yet, but it would be useful. I personally would like to have it in order to auto-collapse long import sections.

**Comment by DoctypeRosenthal** [comment]
Would it be collapse based on indentation?

**Comment by klazuka** [comment]
I would start with the IntelliJ docs:

- [example](http://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support/folding_builder.html)
- [integration tests](http://www.jetbrains.org/intellij/sdk/docs/tutorials/writing_tests_for_plugins/folding_test.html)

and I would look at how the [intellij-rust plugin](https://github.com/intellij-rust/intellij-rust) does it since they tend to do a really nice job (1) adapting the IntelliJ platform to Kotlin and (2) writing tests for new functionality.

- [RsFoldingBuilder](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt)

@ianp was [working on adding code folding](https://github.com/durkiewicz/elm-plugin/pull/48) to Kamil's Elm plugin a few years ago. That might be helpful to look at.

My main advice would be to try to keep it small in scope for now (just collapsing the import section), write tests, and build up from there.

**Comment by DoctypeRosenthal** [comment]
👌

Keith Lazuka <notifications@github.com> schrieb am Di., 14. Aug. 2018,
17:36:

**Comment by klazuka** [comment]
Code folding was implemented in #70. It will be in the next release.
