### ISSUE TITLE
Support Lamdera

### ISSUE THREAD

**Issue by Herteby** [klazuka/intellij-elm#619]
[Lamdera](https://lamdera.com/) uses a fork of the Elm compiler, and uses different directories:
`~/.lamdera/elm` instead of `~/.elm`
`lamdera-stuff` instead of `elm-stuff`
This causes intellij-elm to be unable to find stuff. However, I'm guessing that if only it also looked in those directories, it would probably work!

**Comment by ajalt** [comment]
It seems unrealistic for us to support an unreleased language. But you can make whatever changes you want locally and build the plugin with `./gradlew build`. 

You can install the built plugin by going to the IntelliJ settings > Plugins > ⚙️ > Install Plugin from Disk. The built plugin will be located in `build/distributions`.

![Capture](https://user-images.githubusercontent.com/1109214/75699783-dac4bc00-5c65-11ea-805f-e7883578134e.PNG)

**Comment by klazuka** [comment]
@Herteby I do attempt to use the `ELM_HOME` environment variable when searching for Elm packages. So if you can arrange to launch the IntelliJ UI from an environment where this variable is set appropriately, you might be able to make it work.

Our [nvm docs](https://github.com/klazuka/intellij-elm/blob/master/docs/nvm.md) have a brief description of how this works on Linux. Please let me know if you get it working so that I can add it to the docs.

**Comment by Herteby** [comment]
I got it working in my own hacky way 😄 
* Download the elm 0.19.0 compiler and set that as the compiler for intellij-elm
* Create a symlink:  `ln -s ~/.lamdera/elm/0.19.0 ~/.elm/0.19.0`
