### ISSUE TITLE
Import fix options

### ISSUE THREAD

**Issue by pravdomil** [klazuka/intellij-elm#627]
I have been testing https://github.com/klazuka/intellij-elm/pull/620 and I have found following issue:

Quick fix (alt+enter) suggest `Qualify name` and if I want to do `Import` instead I can't do that anymore.

So can we prefer `Import` over `Qualify name`?

<img width="286" alt="image" src="https://user-images.githubusercontent.com/2387356/76442362-22171f00-63c1-11ea-8d14-9b2ea508b10d.png">

**Comment by ajalt** [comment]
You can still do import like you did before, by moving your cursor over the value, pressing Alt+Enter, then selecting Import. 

I think the default of `Qualify Name` makes more sense, since it only shows up if you've imported the module with an alias. I think most people would want to be consistent and use the alias everywhere in the file. If you don't want the  `Qualify name` fix to show up, then you can remove the alias from your import.

**Comment by pravdomil** [comment]
Interesting, I'm used to use `Decoder` since it's short and easy to read, but I'm using `Decode.string` for the rest since it "decodes string", so that doesn't fit into my workflow. I'm not sure what is the right way how to decide between `Qualify` or `Import`, but I will think about it.

**Comment by klazuka** [comment]
I also do the same thing: when importing types I expose them (unqualified) but functions/values I do not import (qualified).

There is a naming convention in Elm that types can be read standalone but functions/values be named with the assumption that they will be preceeded by a qualifier to disambiguate.

@ajalt would it be possible to use the presence/absence of a qualifier on the unresolved reference to decide what the default fix action should be?

**Comment by pravdomil** [comment]
@klazuka 

> There is a naming convention in Elm

I don't know that, where is the convention defined?

> use the presence/absence of a qualifier on the unresolved reference to decide what the default fix action should be

Can write an example of that?

**Comment by klazuka** [comment]
I'm not aware of an official, documented convention, but that's just how a lot of the standard library modules are written. For instance, in the `Result` module you have the `Result` type and you have the function `andThen`. It's common to use the type exposed (unqualified), but you almost always would qualify `andThen` as `Result.andThen`.

**Comment by ajalt** [comment]
> would it be possible to use the presence/absence of a qualifier on the unresolved reference to decide what the default fix action should be?

I'm not sure I follow; if the qualifier exists, then... it's already qualified and we don't need a fix?

**Comment by klazuka** [comment]
It could be qualified and still not resolve, depending on the imports/aliases. But in any case, my question was no good.

But how about this: if the unresolved ref has a qualifier, then I think it's safe to assume that it's the user's intent to import the module whose name matches (or introduce an alias). If the unresolved ref _does not have_ a qualifier, then let's assume that the user wants to expose the type/value.

So far so good. Now let's assume that there's an un-qualified ref which _could_ be resolved based on existing imports by adding a qualifier. I still think in this case it's better to assume that it's the user's intent to expose rather than to qualify simply based on the fact that they did not write a qualifier.

So I agree with @pravdomil that the 'add import' fix should be higher priority than 'add qualifier'. And this could be achieved by never giving a hint for 'add qualifier'. But maybe there's another use case that I'm missing?

**Comment by pravdomil** [comment]
@ajalt 
> I think the default of Qualify Name makes more sense, since it only shows up if you've imported the module with an alias

That doesn't work for me, today I end up in this situation:

My imports: (no alias)
<img width="688" alt="image" src="https://user-images.githubusercontent.com/2387356/76873099-9cd2b500-686d-11ea-95ac-ae2fdeabf1a3.png">


Before fix:
<img width="481" alt="image" src="https://user-images.githubusercontent.com/2387356/76872884-541afc00-686d-11ea-8fb1-097756c14740.png">

After fix: (does Qualify Name)
<img width="431" alt="image" src="https://user-images.githubusercontent.com/2387356/76872731-174f0500-686d-11ea-9164-6983be005cb6.png">

---

**What I think is the right way to decide between Qualify or Import:**

Alt+Enter does `Import` (same as in any other language) and provide `Qualify Name` on any reference, this way we can do `Qualify Name` whenever we want to, not only when importing.

**Comment by klazuka** [comment]
@pravdomil can you pull the latest from master branch and see how it feels. I want to confirm that the changes match your expectations. It feels good to me, but I only used it briefly for a few minutes.

**Comment by pravdomil** [comment]
compiling...

**Comment by pravdomil** [comment]
found https://github.com/klazuka/intellij-elm/issues/635

**Comment by pravdomil** [comment]
and https://github.com/klazuka/intellij-elm/issues/637 but those are minor related issues so this can remain closed
