### ISSUE TITLE
Run `elm-format` when file saved even when there are syntax errors

### ISSUE THREAD

**Issue by jfmengels** [klazuka/intellij-elm#628]
## Problem

`elm-format` isn't executed when a file is saved, and I think this is because the plugin detects syntax errors (I am not confident in that, but that matches my experiments).

## Motivation

Coming from Atom and `elmjutsu`, I am a bit frustrated with how many more syntax errors I get now compared to with `elmjutsu`.

From what I understand, `elm-format` has looser syntax requirements than IntelliJ, but fixes them when it is run. I show a few examples where `elm-format` fixes the syntax errors below. They already get fixed today when I run `elm-format` from the CLI or from IntelliJ, so it would only be a matter of enabling it on save.

I feel that this would be a huge improvement to the user's experience, especially for newcomers to the language. With `elmjutsu` doing this this way, I never felt that the language was too strict on the syntax (like indentation for instance), but without `elm-format` covering for me, it feels more painful to write Elm.

## Examples of fixed syntax errors

(Would fix the error reported in https://github.com/klazuka/intellij-elm/issues/443 if the users enabled `elm-format` on save)
```elm
-- Doesn't compile
type alias A =
{}
-- After elm-format, compiles
type alias A =
    {}
```
(Would fix the error reported in https://github.com/klazuka/intellij-elm/issues/22 if the users enabled `elm-format` on save)
```elm
-- Doesn't compile
foo =
    a (\x ->
        case x of
            [] -> 0
            _ -> 1)
-- After elm-format, compiles
foo =
    a
        (\x ->
            case x of
                [] ->
                    0

                _ ->
                    1
        )
```
```elm
-- Doesn't compile
type alias A =
    { a = Int }
-- After elm-format, compiles
type alias A =
    { a : Int }
```
```elm
-- Doesn't compile
value =
    { a : 1 }
-- After elm-format, compiles
value =
    { a = 1 }
```
```elm
-- Doesn't compile
func a =
    let
b = 1
    in
    a
-- After elm-format, compiles
func a =
    let
        b =
            1
    in
    a
```

## Thanks

I will use this opportunity to thank you for the hard work you have put into this project. It is really a splendid tool :heart:

**Comment by klazuka** [comment]
You're right: intellij-elm does not run elm-format on-save when there are known syntax errors in the current file.

But I am interested in your case, and so I just tried playing with allowing elm-format to run even if there are syntx errors. Unfortunately the problem is that in cases where elm-format cannot successfully run, it dumps out the parse errors straight from the compiler in textual, ANSI color format. Reading this in a popup notification is not pleasant.

It would be nice if elm-format supported passing the compiler errors through as JSON so that we could use our existing UI to display the errors nicely. But I don't see an option for that.

How did elmjutsu display the errors when `elm-format` ran into unrecoverable parse errors?

**Comment by jfmengels** [comment]
Oops, I'm sorry, it was not `elmjutsu` but the [`elm-format` Atom plugin](https://github.com/humio/atom-elm-format).

Anyway, this is the result when you have a syntax error: A (not very helpful) notification in the top-right corner
![Screenshot from 2020-03-12 19-06-05](https://user-images.githubusercontent.com/3869412/76553568-9078e180-6494-11ea-8099-2d6d7ade2c4a.png)

I have checked, and `elm-syntax` exits with status code 0 when there are syntax errors that it can (and does) fix.
I have also looked at the code, and here is the section that deals with when `elm-format` exits with an error code.
https://github.com/humio/atom-elm-format/blob/master/src/index.js#L100-L128

So basically, they strip the ANSI codes and whatever information that is not really relevant, find the line number in order to create something actionable like "Jump to Syntax Error" (which doesn't really work for me).

The reason why I was confused about `atom-elm-format`/`elmjutsu` is that after that, I then see this (more helpful) compiler error message, that `elmjutsu` creates because the compiler returned with an exit code.

![Screenshot from 2020-03-12 18-47-49](https://user-images.githubusercontent.com/3869412/76551741-d2edee80-6493-11ea-9b63-7599eac3154d.png)


Summary:
- `atom-elm-format` tries to run `elm-format`
  - If it succeeds, it fixes the file (even)
  - It it fails, it creates an error notification just to get the line number
- `elmjutsu` comes in and runs the compiler, which gives me a useful error message


I think that in the case of this plugin, you can run `elm-format` on every save, and if it exits with status code 1, you pretty much ignore the error message, and use the current behavior to indicate there is a syntax error.

**Comment by klazuka** [comment]
Ah, I see. Thanks for digging into this. 

I like the idea of silencing the elm-format error caused by syntax errors during format-on-save. That could work.

My only reluntance is what if elm-format tries to recover the bad syntax in a way that you did not intend. Have you had any problems with that?

**Comment by jfmengels** [comment]
> if elm-format tries to recover the bad syntax in a way that you did not intend. Have you had any problems with that?

I don't feel like I have no. These fixes are relatively simple. The only unintended fixes I notice are ones that happen when the syntax is correct.

**Comment by lydell** [comment]
I recently learned on the Elm Town podcast that elm-format can fix `type alias Foo = { foo = Int }` into `type alias Foo = { foo : Int }`. When trying this feature out, I was confused because I tried it via format-on-save in IntelliJ. Now I understand why it didn’t work! (Running format via keyboard shortcut works, fortunately.)

I’d also like it if elm-format was (attempted to be) run on save even if there are syntax errors.

**Comment by avh4** [comment]
> Unfortunately the problem is that in cases where elm-format cannot successfully run, it dumps out the parse errors straight from the compiler in textual, ANSI color format. Reading this in a popup notification is not pleasant.

FYI, I am planning to slowly remove details from the elm-format error messages, since they eventually drift out of date from elm-compiler which is striving to improve the error messages.  Specifically, as soon as I get around to it, I'd like to try having elm-format simply say something brief like "there was an error on line X.  For a detailed error message, run elm make".

Imo an appropriate thing for editor plugins to do is to ignore the console output of elm-format when it fails.

**Comment by avh4** [comment]
> My only reluntance is what if elm-format tries to recover the bad syntax in a way that you did not intend. Have you had any problems with that?

I'm trying to make sure I only make elm-format lenient in ways that are unambiguous.  So if there are issues with this (now or in the future), I'd like to fix those in elm-format itself.

**Comment by cmditch** [comment]
Agreed, this would be very nice. I miss the syntax corrections elm-format makes while using it with intellij.
