### ISSUE TITLE
Autocomplete Record Field names

### ISSUE THREAD

**Issue by ryancerf** [klazuka/intellij-elm#680]
Before completion.
```elm
type alias Foo = { name : String }

f : Foo
f =
    { n{-caret-} }
```

After completion
```elm
type alias Foo = { name : String }

f : Foo
f =
    { name = {-caret-} }
```

**Comment by ryancerf** [comment]
Hi,

First off, thanks for the awesome plugin. I started playing around with a few possible implementations and would love to get your advice on how to approach this.

Couple of options:

1) Use the existing diagnostics field on `InferenceResult`.
Parse the diagnostics on `InferenceResult` looking for a `TypeMismatchError` with missing fields on the `recordDiff`. This is easy, but will not work in some situations such as nested records. It will probably get us 60% of the way there and I could send a PR in a day or two.

2) Add information to `InferenceResult` that identifies the expected (declared) types of expressions.
This is a much heavier lift since it requires touching the type inference code, but if we were able to expose the declared types in a general way it would make it possible to add lots of autocomplete functionality though out the plugin.

**Comment by klazuka** [comment]
Using the Diagnostics is a clever idea. It was definitely intended only for display purposes, but I guess there's no technical reason why you couldn't use it other than objections based on purity. I wouldn't be strictly opposed to it.

Changing `InferenceResult` is trickier as there can be some gotchas. The type inference data is heavily cached, and so we want to keep the size of the in-memory data small. And you have to be careful about the caching because we are caching mutable objects and promising not to mutate them after. (not sure if that would be a problem in this case, but just wanted to mention it).

You mentioned that the Diagnostics-based solution would only cover some of the situations. Which situations did you have in mind that wouldn't be covered? Where there is no type annotation?

**Comment by ryancerf** [comment]
Thanks for the quick response.

Using the diagnostic solution the only place I have found so far where I would like autocomplete to work but it does not is inside a nested record. 

```elm
// no completions
type alias Foo = { name : { first: String } }

f : Foo
f =
    { name = { f{-caret-} } }
```

The `recordDiff` on the diagnostic is at the parent level (`Foo`) which makes it hard to find the missing fields on the nested record`{ first: String }`.

Here is the diagnostic from the example above.

![Screen Shot 2020-08-15 at 12 06 27 PM](https://user-images.githubusercontent.com/7135877/90319749-c57bdb00-deef-11ea-9850-18554cd84167.png)


Options
* I could try to use the names of the ancestor ElmField's to traverse the parent type to find the relevant nested child type. This feels like a hack.
* We could adjust the diagnostic code to return a diagnostic for the child record instead of the parent or possibly multiple diagnostics depending on the situation.
* We could skip fixing this for now because having this working in some situations is better than none.

Thoughts?

#### The diagnostic solution _does_ work in these situations:
*  In a record update expression expression
*  In a Let in expression
*  A record in a custom type  `type Bar = Baz {name:String}`
*  In a case expression (where there is no annotation and the type is inferred from the first branch)
* Where the field value is already set `{ {-cursor-} = "elm" }`

If you want more detail let me know. I can create a PR so you can preview the tests I have so far.

**Comment by klazuka** [comment]
The nested record case is rare enough that I don't think it's worth the extra work (at least for now). 

Go ahead with your diagnostic based solution. I'll review the PR.
