### ISSUE TITLE
Renaming a shadowed function incorrectly renames the shadowed variable

### ISSUE THREAD

**Issue by mordrax** [klazuka/intellij-elm#76]
```
-- this causes a 0.19 error about shadowing.
-- the function name shadows the destructured variable of the same name

medicareGivenNames : { a | medicareGivenNames : String } -> (String -> msg) -> Html msg
medicareGivenNames { medicareGivenNames } msg =
    View.Layout.paneField "Medicare Name" (View.Components.input medicareGivenNames msg)

-- a refactor rename yields the following
-- note that the variable used in the `View.Components.input` is incorrectly renamed as well

viewMedicareGivenNames : { a | medicareGivenNames : String } -> (String -> msg) -> Html msg
viewMedicareGivenNames { medicareGivenNames } msg =
    View.Layout.paneField "Medicare Name" (View.Components.input viewMedicareGivenNames msg)
```

This is a fairly trivial issue to fix up though. The usage of the function elsewhere are updated correctly and this is mostly a once off issue with 0.18 -> 0.19 upgrades.

**Comment by klazuka** [comment]
You're right that this will be less of an issue in 0.19, but we should still fix it. Thanks for reporting.

The fix is probably just to make sure that the PsiReference variants in lexical scope are sorted such that the parameters to a function come before the function name itself. It's undocumented how the Elm compiler resolves names, but this would probably be close enough for now.

**Comment by klazuka** [comment]
Actually, there is no right solution here. Because if I do what I said above (the parameter resolves before the function name), then it would be wrong in this case:

```elm
bar : { bar : String } -> Html msg
bar { bar } =
    bar { bar = "" }
    --^
```

If the cursor is where the comment-caret thing indicates, then that name *should* resolve to the function itself (recursive). But if I make the change you're asking for, it would instead resolve to the destructured record field name parameter--which would be wrong.

So either way we lose. The ultimate problem is that the name shadowing creates an ambiguous situation, and it's up to the user to sort out the mess. The rename refactoring just makes it look like it's our fault, but garbage-in, garbage-out.
