### ISSUE TITLE
Retrieve compiler output color information

### ISSUE THREAD

**Issue by mordrax** [klazuka/intellij-elm#83]
When compiling in webstorm ( via hotkeys ), the console's output is in one color (even though it supports colors). In elm 0.19, some error messages are only useful in color:
https://github.com/elm/error-message-catalog/issues/269

Evan mentioned that the compiler colors can be found in the following package:
https://package.elm-lang.org/packages/elm/project-metadata-utils/latest/

It would be _awesome_ if this plugin could relay this information to the console.

More info:
Webstorm allows you to configure colors and font for their console. 
There are plugins for embedding a terminal, even a iTerm.
But you cannot link the output of a external tool to a terminal, and you cannot set the console to be colored like a terminal.

**Comment by klazuka** [comment]
I haven't yet looked at the Elm 0.19 output, but the problem with 0.18 was that it was too smart: it would disable ANSI color codes if it wasn't running in a TTY. Not sure if that's still true.

My plan is to do some kind of build / run-config integration in the near future. Having colored error output is a must!

**Comment by clojj** [comment]
started looking at elm's 0.19 compiler output, and also at the output from `elm make ... --report=json`
I too think that having the original (colored!) output in the console is a must.
It would also be great to have some custom hints/output for easy navigation between all of elm's errors.

..any other ideas about this currently ?

**Comment by klazuka** [comment]
It's less useful now that we do type-checking in the plugin itself (although that's not 100% fully implemented yet). But, nevertheless, it will be nice to able to invoke `elm make`, and I started laying the groundwork for it already (`org.elm.workspace.ElmBuildAction`).

There's nothing stopping us from doing it, just lack of time and not being high enough priority IMHO.

On a side-note, we've started working on integrating elm-format more tightly, and when you invoke that with syntax errors, it spits out colored output that would be nice to show to the user. So maybe it would be better to just figure out how to display ANSI colored output in an IntelliJ tool window rather than trying to parse `elm make`'s JSON output?

At some point we definitely *will* want to parse the JSON report from the compiler, but that would come after displaying colored ANSI output.

**Comment by clojj** [comment]
https://upsource.jetbrains.com/idea-ce/file/idea-ce-a7b3d4e9e48efbd4ac75105e9737cea25324f11e/platform/platform-api/src/com/intellij/execution/process/ColoredProcessHandler.java

and

https://upsource.jetbrains.com/idea-ce/file/idea-ce-a7b3d4e9e48efbd4ac75105e9737cea25324f11e/platform/lang-api/src/com/intellij/execution/filters/Filter.java

should be relevant here

**Comment by clojj** [comment]
I will try to make a PR for this...

**Comment by klazuka** [comment]
The other thing to take into consideration is that, I believe, Elm tries to be smart and only emit color when it thinks that a terminal (capable of color) is attached. Not sure what it will think when IntelliJ/Java invokes the process.

**Comment by tigp** [comment]
Guys, maybe that would be interesting for you. I just created a small tool, it uses `elm make ... --report=json`, parsing json and outputs short colored error message with clickable path:row:column . It can be used with JetBrains console and by installing the JetBrains Grep Console plugin it can clear the output for every reload so that there is no scrolling to the previous output. It also debounce multiple saves so there is no blinking. https://github.com/tigp/elm-short-clickable-errors

**Comment by klazuka** [comment]
That's really cool. If someone were to port the logic for parsing Elm's compiler output into IntelliJ's hyperlinkable text format, then we would be a lot closer to building this into the plugin itself.

As I understand it, the major pieces are:

1. an action to trigger a build (already implemented in `org.elm.workspace.ElmBuildAction` but not currently exposed to users). Alternatively, a Run Configuration. 
2. the ability to invoke the Elm binary as an external process (already implemented in `org.elm.workspace.ElmCLI` but needs to be generalized a bit)
3. some logic to find the Elm program's main entry point (use `ElmLookup` to find function declarations with the name `main` and then look for one whose type is `Program`). Alternatively, if we're using a Run Configuration we could have the user tell us where `main` is, but it'd be nicer to determine it automatically)
4. parse the output of `elm make` using @tigp's code as a reference
5. display the output in a tool window (already implemented in `org.elm.workspace.ElmBuildAction` but will need some polish)

**Comment by tigp** [comment]
If that is going to be part of the plugin that would be fantastic!

**Comment by tigp** [comment]
The version I created yesterday didn't work with all the errors, I changed it and now it seems to be showing everything correctly.

**Comment by clojj** [comment]
@klazuka 
I experimented a bit and I think that after parsing the JSON output from Elm, we can build linked-up (source locations) and styled (background, foreground, font-weight etc.) content in the existing toolwindow, for example arrange in a vertical layout.

This would replace the 'console style' rendering by clickable lables (IntelliJ's LinkLabel for example).
I think this will make navigation between each error-message easier...

**Comment by clojj** [comment]
btw, I think parsing the JSON and mapping some styles is the easy part ;)

**Comment by klazuka** [comment]
@clojj sounds good, go for it. And let me know if you need any guidance. I'm happy to help.

**Comment by clojj** [comment]
I am completely lost at the moment, in what would be the most effective way to present these messages..

**Comment by klazuka** [comment]
Do you have a branch that I can look at? I’m not familiar with the IntelliJ APIs related to this specific feature, but I have become adept at digging in and figuring things out.

**Comment by clojj** [comment]
I like this arrangement a lot

![elm-toolwindow](https://user-images.githubusercontent.com/4367963/52975588-60acf680-33c6-11e9-9de9-7225abb7bbe3.png)

**Comment by clojj** [comment]
do this:
go to some symbol, then Ctrl-Q, then option (cogwheel) "Open as Tool Window"

**Comment by clojj** [comment]
yet another possibility

![ij-elm-1](https://user-images.githubusercontent.com/4367963/52975853-68b96600-33c7-11e9-94f1-ae70aab5b4ef.png)

**Comment by clojj** [comment]
But:
- how to wrap, if the (error)text is too long ?
or
- how to adjust the width ?

also
- make it scrollable ?
- have it (or a tab?) show _all_ errors too ?

**Comment by tigp** [comment]
The first one is definitely the best! Is it going to show all the errors in the project so that you'd navigate to different files from it? 

Maybe wrapping is unnecessary as I'd guess it's going to be used in the bottom. I tried to put the window on the right and it's just not the best experience.

Also wanted to say that there are at least 3 types of outputs that elm make produces - empty, one for single error - ex. invalid module exposing etc. and another that contains multiple errors - ex. syntax errors. Maybe that would be helpful.

**Comment by clojj** [comment]
this is a rant (sorry).... looking at the source of this (QuickDoc feature) in IJ community edition is nightmare-ish

**Comment by tigp** [comment]
I think the panels that are supposed to show current state that you supposed to look at often are in the bottom - Run, Debug, Terminal, left is for file, methods navigation and right is for things like controlling the database or something that you use occasionally, if left and right panels are going to be open all the time it's just going to take too much space. This is how the elm output looks like on the right with wrapping:

![screenshot 2019-02-18 22 59 00](https://user-images.githubusercontent.com/24852530/52978412-7ffd5100-33d1-11e9-9793-c24ac1aa4d13.png)

**Comment by klazuka** [comment]
Ideally almost all errors will be caught by the plugin itself (syntax, type checker, etc.), but due to how IntelliJ is designed, that will only covers files that are open in the editor. In order to provide a list of all errors across the project, the user should be able to invoke the Elm compiler. So the way I see this feature is more of a fallback rather than the principle way of viewing errors.

Here's the rough idea of what I have in mind:
1. User invokes an Elm build via `ElmBuildAction` (to-be-decided how this will appear in the UI)
2. `elm make` is invoked purely for error checking (generated code goes to `/dev/null`)
3. A tool window (usually hidden) pops up at the bottom of the screen. It shows a list of errors, each one is clickable, and when it's clicked, the main source editor navigates to its position.

So it's kinda like https://github.com/tigp/elm-short-clickable-errors, but with a few differences:
- since we control the tool window console, we won't need to do the "CLEAR CONSOLE" grep console hack (also no dependency on the Grep Console plugin)
- no file watching (always invoked explicitly by the user)

Some day we may want to do things like file watching and launching a web-server with the generated code, injecting hot module reloading (https://github.com/klazuka/elm-hot), etc. but for now let's try to keep it as focused as possible on making it easy for a user to fix all of the compile errors in their project.

This is all a long way of saying that I don't think we need the tool window to live update based on where the user's caret is 😄. That would be cool, but there's enough work to be done that we should try to keep things as simple as possible.

**Comment by tigp** [comment]
I just added a branch that is supposed to be used with File Watcher, no dependencies needed, it can always show the Output panel or only when the errors are present, it clears automatically https://github.com/tigp/elm-short-clickable-errors/tree/for-jetbrains-file-watcher. I've added images of how it looks inside the branch. Maybe that would be useful.

**Comment by clojj** [comment]
Agreed.. I would suggest using a Swing component UI (JLabel, Linklabel,
...) for the bottom Toolwindow, not a console.

That way we have better options for styling and easier keyboard event
handling as far as I can tell from IJ API

**Comment by clojj** [comment]
The json parsing was a bit trickier than expected, but here is an preliminary example output (colors and styles of course have to be optimized)
![intellij-elm-example](https://user-images.githubusercontent.com/4367963/53304513-9181a580-3876-11e9-85d4-b234b2e74db8.png)

**Comment by klazuka** [comment]
Nice!

Let me know when your branch is in a good state and you want me to give it a try.

**Comment by clojj** [comment]
demo of 'Navigate to source' aka F4
![intellij-elm-demo](https://user-images.githubusercontent.com/4367963/53306646-07ded180-3890-11e9-8589-3fd2cb1016de.gif)

**Comment by clojj** [comment]
got some merge conflicts from upstream/master... will take a while to resolve these..
(ElmCLI and other refactorings)

**Comment by klazuka** [comment]
Yeah, sorry about that. I had to do a major overhaul in `ElmToolchain` because the old idea of just configuring a single directory that contains all of the Elm-related tools turned out to be too restrictive.

**Comment by klazuka** [comment]
@clojj demo looks cool. Would it be possible to change the "Compiler Output" pane to be master-detail where the left-side contains a list of errors, and the right-side contains the error detail ouptut (like you have now)?

The advantages would be:
- gives an overview of how many errors there are (and in which files)
- allows for non-sequential navigation

I'd also be fine with deferring that to a later PR in order to keep the scope limited.

**Comment by clojj** [comment]
I noticed java code related to json parsing (?)
are you working on this too ?

**Comment by clojj** [comment]
ah I see... it is about elm-test
but we can probably share some data classes for the json report...

**Comment by klazuka** [comment]
@clojj yes, we just merged that in. @frawa did all of the work related to elm-test. But I don't think there's any similarity between the JSON output of `elm-test` and that of `elm`.

**Comment by clojj** [comment]
@klazuka ok, thx for the update
that split between the list-overview (left) and full message (right) is a good idea.. I willl give it a shot

For advanced Elm developers, just navigating the shorter list-descriptions (left) is more effective most of the time anyway...

**Comment by clojj** [comment]
![intellij-elm-toolwindow](https://user-images.githubusercontent.com/4367963/53372249-a6336b80-3952-11e9-82b0-f76d1b68554f.png)
...of course, the error-list has to get some better visual design

**Comment by clojj** [comment]
@klazuka 
    // TODO [kl] allow the caller to specify the main entry point Elm file

Is there any code already, allowing me to determine the main entry module ?

**Comment by clojj** [comment]
what currently works...

![intellij-elm-demo](https://user-images.githubusercontent.com/4367963/53446068-51efc080-3a12-11e9-9558-000ac7a26fbb.gif)

**Comment by klazuka** [comment]
The short answer is no. However, at the time that I wrote that comment, there was no concept of an `ElmWorkspace` nor `ElmProject`. We weren't even reading the `elm.json` files off the disk, and so we didn't know where the source-directories were. And we also didn't have type inference. We're in a much better place now, so I don't expect that it will be too difficult.

I would probably implement this by calling `org.elm.lang.core.lookup.ElmLookup#findByName` with name being "main" and the return type being `ElmFunctionDeclarationLeft` (confusing, i know, but this indicates that we're looking for a function named `main`).

This will get you close, but you will still need to look at the type annotation to determine if it really is an entry point (I didn't do this in the unused code inspection because I could live with the false negative, at least temporarily).

This is where things get a little tricky.

- the function may or may not have a type annotation
- main entry points can be of type `Platform.Program` (most common) or `Html` (toy programs)
- the packages that provide these types are named differently in Elm 0.19 and 0.18

The correct thing to do would be to infer the type of the function. Use `org.elm.lang.core.types.TypeInferenceKt#findInference` on the result from `ElmLookup`, and then access the `ty` property on the `InferenceResult` to get the type of the function. You'll have to play around with it a bit, but I think what you'll want to look for is a `TyUnion` where module="Platform" and name="Program" **or** module="Html" and name="Html".

**Comment by klazuka** [comment]
@clojj the demo looks nice!

**Comment by clojj** [comment]
@klazuka 
ok, so would a new plugin-setting "Elm Compiler - path to main Module" be ok, until we tested your proposed lookup enough ?
I mean, only when the user enters a valid path, the (Compiler-)toolwindow would activate...

**Comment by klazuka** [comment]
I would rather not introduce an additional configuration setting. I think the technique that I described above should be sufficient.

**Comment by clojj** [comment]
btw, you can review/test here https://github.com/clojj/intellij-elm/tree/elm-compiler-with-messages-toolwindow

**Comment by clojj** [comment]
> I would rather not introduce an additional configuration setting. I think the technique that I described above should be sufficient.

ok, so I will look into it...

**Comment by clojj** [comment]
without an explicit type signature, I get this (TyUnknown)

![main-searching](https://user-images.githubusercontent.com/4367963/53513303-24178400-3ac5-11e9-9348-777629c7c491.png)

**Comment by klazuka** [comment]
Hmm. I was worried that this might be the case because of the last remaining limitation in the type system implementation (type variables are unified only when they are explicitly declared in a type annotation).

But when I tested it without a type annotation on `main`, it worked (in my case I was using `Browser.application`).

Let's do this: if `main` cannot be found because its type is unknown, display a message to the user asking them to add a type annotation to their `main` function. That way it will just work once the type system is fully implemented.

We may need to come up with additional heuristics in the future, but this should be good enough for now.

**Comment by clojj** [comment]
got something to look at in that branch I told you

**Comment by klazuka** [comment]
let's move the conversation over to the PR (#332)

**Comment by klazuka** [comment]
I just released [version 3.1.0](https://github.com/klazuka/intellij-elm/releases/tag/v3.1.0) which includes this feature. It's available now from the GitHub release, or you can wait about 24 hours for it to become available via JetBrains plugin repository.
