### ISSUE TITLE
using << to compose functions creates irrelevant error

### ISSUE THREAD

**Issue by psyCodelist** [klazuka/intellij-elm#90]
Hello,

Thank you for the amazing plugin!

`(Url.percentEncode << String.replace "\"" "\\\"") query` <- error here
generates error but should be ok.

**Comment by klazuka** [comment]
@ajalt this may be a regression caused by our recent parser changes related to parenthesized expressions, operators, function calls, etc. It happens for any binary operator, not just `<<`, and it only happens when an operand comes _after_ the parenthesized expression containing a binary operator.

Here's a simpler example that compiles in Ellie but is a parse error in our plugin:
```elm
main = text foo

foo =
    (identity << identity) "42"
```

**Comment by psyCodelist** [comment]
@klazuka thanks for the follow up.
another issue that I see is:

sat you have a record like `type alias  Permission = { canEdit : Bool, canDelete: Bool }`

if you use record property as function it creates an error:

`.canEdit myPermission` <- error

**Comment by klazuka** [comment]
@psyCodelist thanks for reporting this. I just released a new build with the parser fix. You can download it from https://github.com/klazuka/intellij-elm/releases/tag/v1.3.3 or you can wait for the build to become available via JetBrains (up to 2 business days, so possibly as late as Monday).

**Comment by psyCodelist** [comment]
Thank you all. really appreciate it.
